// Semantic VS Code identifiers come first; their registered Codicon defaults
// follow. One mapping drives both rendering and the built-in VSIX export.
export const productIcons = {
  ArrowDown: ["arrow-down"],
  ArrowLeft: ["arrow-left"],
  ArrowRight: ["arrow-right"],
  ArrowUp: ["arrow-up"],
  CaseSensitive: ["search-case-sensitive", "case-sensitive"],
  Check: ["check"],
  ChevronDown: ["chevron-down"],
  ChevronLeft: ["chevron-left"],
  ChevronRight: ["chevron-right"],
  ChevronsDownUp: ["collapse-all"],
  ChevronsUpDown: ["expand-all"],
  CircleAlert: ["error"],
  Circle: ["circle-outline"],
  Code: ["code"],
  Columns2: ["split-horizontal"],
  Command: ["symbol-key"],
  Copy: ["copy"],
  Download: ["cloud-download"],
  Ellipsis: ["more"],
  ExternalLink: ["link-external"],
  Eye: ["eye"],
  EyeOff: ["eye-closed"],
  File: ["file"],
  FileCode: ["file-code"],
  FileDiff: ["diff"],
  FileJson: ["json"],
  FilePlus2: ["explorer-new-file", "new-file"],
  FileText: ["file-text"],
  Folder: ["folder"],
  FolderOpen: ["folder-opened"],
  GitBranch: ["git-branch"],
  GitCommitHorizontal: ["git-commit"],
  Globe: ["globe"],
  History: ["history"],
  Import: ["import"],
  Info: ["info"],
  Keyboard: ["keyboard"],
  Layers: ["layers"],
  LayoutGrid: ["layout"],
  ListX: ["clear-all"],
  Maximize2: ["screen-full"],
  Menu: ["menu"],
  Minimize2: ["screen-normal"],
  Minus: ["remove"],
  Monitor: ["device-desktop"],
  Moon: ["moon"],
  Palette: ["color-mode"],
  PanelLeft: ["layout-sidebar-left"],
  PanelRight: ["layout-sidebar-right"],
  Pencil: ["edit"],
  Pin: ["pin"],
  PinOff: ["pinned-dirty", "pin"],
  Play: ["play"],
  Plus: ["add"],
  Puzzle: ["extensions"],
  Redo2: ["redo"],
  RefreshCw: ["refresh"],
  Regex: ["search-regex", "regex"],
  RotateCcw: ["discard"],
  RotateCw: ["refresh"],
  Save: ["save"],
  Search: ["search"],
  Settings: ["settings-gear", "gear"],
  ShieldCheck: ["shield"],
  Square: ["primitive-square"],
  SquareArrowRight: ["sign-out"],
  SquareDot: ["record-small"],
  SquareMinus: ["diff-removed"],
  SquarePlus: ["diff-added"],
  Sun: ["lightbulb"],
  Terminal: ["terminal"],
  Trash2: ["trash"],
  Undo2: ["undo"],
  WholeWord: ["search-whole-word", "whole-word"],
  WrapText: ["word-wrap"],
  X: ["close"],
} as const;

export const contextProductIcons = {
  "chrome-minimize": "Minus",
  "chrome-maximize": "Square",
  "chrome-close": "X",
  "dialog-close": "X",
  "tab-close": "X",
} as const satisfies Record<string, keyof typeof productIcons>;
