export const cliNames = {
  codex: "Codex",
  agy: "Antigravity CLI",
  cursor: "Cursor CLI",
  claude: "Claude Code",
  gemini: "Gemini CLI",
  copilot: "GitHub Copilot CLI",
  opencode: "OpenCode",
  openclaw: "OpenClaw",
  hermes: "Hermes Agent",
  pi: "Pi Coding Agent",
  aider: "Aider",
  goose: "Goose",
  cline: "Cline CLI",
  kilo: "Kilo Code CLI",
  qwen: "Qwen Code",
  kiro: "Kiro CLI",
  droid: "Factory Droid",
  openhands: "OpenHands CLI",
  continue: "Continue CLI",
  amp: "Amp CLI",
  auggie: "Auggie",
  crush: "Crush",
  vibe: "Mistral Vibe",
  kimi: "Kimi Code CLI",
  interpreter: "Open Interpreter",
  grok: "Grok Build",
  junie: "Junie CLI",
  deepagents: "Deep Agents Code",
  freebuff: "Freebuff CLI",
  trae: "Trae Agent",
  sweagent: "SWE-agent",
} as const;

export type CliAgent = keyof typeof cliNames;
